### PR TITLE
:Fire(self) now requires tuple

### PR DESCRIPTION
**Pull request by jmesrje**
Changed 'requires table' to converting tuple -> table

### CODE REVIEW

**Comment by ffrostfall** [comment]
Why should I do this? A large part of why I remade BridgeNet was to escape the awfulness of tuples.

**Comment by jmesrje** [comment]
I feel like requiring a table of parameters isn't user friendly over just requiring a tuple. Your choice of course.

**Comment by ffrostfall** [comment]
Sorry, going to have to close this one, we have a singular parameter for a lot of reasons.

**Comment by jmesrje** [comment]
Perfectly fine! I guess it wouldn't be a big deal anyways.

**Pull request closed without merging**
